const main = document.querySelector('main');
document.querySelector('#year').textContent = new Date().getFullYear();
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let works = [];
const urlFor = work => '/?work=' + encodeURIComponent(work.slug);
function render() {
  const slug = new URLSearchParams(location.search).get('work');
  const work = works.find(w => w.slug === slug);
  if (slug && !work) { main.innerHTML = '<section class="empty"><h1>这件作品还未收录。</h1><a href="/">返回作品集 ↗</a></section>'; return; }
  document.title = work ? `${work.title} — NakanoIchirou` : 'NakanoIchirou — 创作集';
  if (work) {
    main.innerHTML = `<section class="work-heading"><a class="back" href="/#works">← 全部作品</a><div class="eyebrow">${esc(work.category)} / ${esc(work.year)}</div><div class="title-row"><h1>${esc(work.title)}</h1><span>${esc(work.englishTitle)}</span></div><p>${esc(work.summary)}</p></section><section class="screen" aria-label="影片播放器"><video id="film" controls playsinline preload="metadata" poster="${esc(work.poster)}"><source src="${esc(work.video)}" type="video/mp4">你的浏览器不支持视频播放，<a href="${esc(work.video)}">可打开影片文件观看</a>。</video><p id="video-error" hidden>影片暂时无法载入，请刷新页面或稍后重试。</p></section><div class="film-bar"><span>${esc(work.duration)} / ${esc(work.format)}</span><a href="${esc(work.video)}" download="硅晶之梦.mp4">下载影片 ↓</a></div><section class="project-body"><div class="section-label">01 / 关于作品</div><div><h2>日常，成为系统的一部分。</h2><p>${esc(work.description)}</p><p>${esc(work.note)}</p><div class="chapter-list" aria-label="跳转至影片章节">${work.chapters.map(ch => `<button type="button" data-time="${ch.time}"><span>${Math.floor(ch.time/60).toString().padStart(2,'0')}:${Math.floor(ch.time%60).toString().padStart(2,'0')}</span>${esc(ch.label)}<span aria-hidden="true">↗</span></button>`).join('')}</div></div></section><section class="stills-section"><div class="section-label">02 / 影像切片</div><div class="stills">${work.stills.map((src,i) => `<figure><img loading="lazy" src="${esc(src)}" alt="《${esc(work.title)}》影片画面 ${i+1}"><figcaption>FRAME / 0${i+1}</figcaption></figure>`).join('')}</div></section><a class="end-link" href="/#works">回到作品集 <span>↗</span></a>`;
    const video = document.querySelector('#film');
    video.addEventListener('error', () => document.querySelector('#video-error').hidden = false);
    document.querySelectorAll('[data-time]').forEach(btn => btn.addEventListener('click', () => { video.currentTime = Number(btn.dataset.time); video.play().catch(() => {}); video.scrollIntoView({behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block:'center'}); }));
  } else {
    main.innerHTML = `<section class="hero"><div class="eyebrow">个人创作集 / AN OPEN COLLECTION</div><div class="hero-grid"><div class="hero-copy"><h1>在日常之外，<br>让想象<span class="red">成形。</span></h1><p>影像、故事，以及尚未被命名的想法。<br>这里收藏我的创作，也为下一次探索留白。</p><a class="text-link" href="#works">探索作品 <span>↘</span></a></div><div class="geometry" aria-hidden="true"><div class="geo-top"><span class="circle"></span><span class="grid-lines"></span></div><div class="geo-bottom"><span class="triangle"></span><span class="square"><i></i></span></div><span class="geo-caption">FORM / RHYTHM / IMAGINATION</span></div></div><div class="hero-bottom"><span>NAKANOICHIROU</span><span>持续生长的作品集 ↓</span></div></section><section class="works" id="works"><div class="section-heading"><h2>作品<span class="small-en">SELECTED WORKS</span></h2><span class="count">${String(works.length).padStart(2,'0')} 件收录</span></div>${works.map((w,i) => `<a class="work-card" href="${urlFor(w)}" aria-label="观看《${esc(w.title)}》"><div class="work-image"><img src="${esc(w.poster)}" alt="《${esc(w.title)}》影片画面"><span class="image-index">${String(i+1).padStart(2,'0')} / ${esc(w.year)}</span><span class="play"><span aria-hidden="true">▶</span> 观看作品</span><span class="duration">${esc(w.duration)}</span></div><div class="work-caption"><div><h3>${esc(w.title)}<span>${esc(w.englishTitle)}</span></h3><p>${esc(w.summary)}</p></div><span class="work-arrow" aria-hidden="true">↗</span></div></a>`).join('')}</section><section class="about" id="about"><div class="section-label">02 / 关于这里</div><div><h2>作品先说话。<br>其余的，慢慢生长。</h2><p>我是 NakanoIchirou。这里是我的个人创作空间，用来保存完成的作品，也记录想象留下的形状。</p><p>从一部影像开始，向更多故事延伸。</p><div class="about-sign"><span class="mini-circle" aria-hidden="true"></span><span>NakanoIchirou<br><small>创作，未完待续。</small></span></div></div></section>`;
    if (location.hash) requestAnimationFrame(() => document.getElementById(location.hash.slice(1))?.scrollIntoView());
  }
}
fetch('/works.json').then(r => { if (!r.ok) throw Error('load'); return r.json(); }).then(data => { works = data; render(); }).catch(() => { main.innerHTML = '<section class="empty"><h1>作品集暂时无法载入。</h1><p>请刷新页面重试。</p></section>'; });
